name: BirazDahaEklenti
main: io.cengiz.bukkit.BirazDahaEklenti
version: 0.2

commands:
   basla:
      description: Bu güzel bir komuttur
      usage: /basla
   bitir:
      description: Bu da güzel bir komuttur
      usage: /bitir
